name: Deploy to Reg.ru

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT || '22' }}
          local_path: "./build/*"
          remote_path: ${{ secrets.REMOTE_PATH }}
          delete_remote_files: true # Очистить папку перед заливкой
