name: Deploy to Reg.ru (FTPES)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy via FTPES
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT || '21' }}
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftpes' }}
          local-dir: ./build/
          server-dir: ${{ secrets.REMOTE_PATH }}
          exclude: |
            .DS_Store
            *.map
